//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseReportApp.Data
{
    using CompanyX.Data.ModelMetadata;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(IExpenseReportMetadata))]
    public partial class ExpenseReport : IExpenseReportMetadata
    {
        public int ExpenseReportID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public string UserID { get; set; }
        public Nullable<decimal> ExpenseTotal { get; set; }
    }
}
