//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseReportApp.Data
{
    using CompanyX.Data.ModelMetadata;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ILineItemMetadata))]
    public partial class LineItem : ILineItemMetadata
    {
        public int LineItemID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ExpenseReportID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
